name: Build Image KM

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  GOGC: 50

jobs:
  main:
    runs-on: arc-runner-set-na
    container:
      image: ubuntu:latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Install buildah
        run: |
          . /etc/lsb-release && \
          apt-get update && \
          apt-get install -y buildah
          buildah version
          echo 'unqualified-search-registries = ["docker.io"]' >> /usr/share/containers/containers.conf

      - name: Build
        uses: redhat-actions/buildah-build@v2
        with:
          image: cert-manager-webhook-netactuate
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Dockerfile
